### ISSUE TITLE
nice to have a createQueryRender HoC to replace the <QueryRender />

### ISSUE THREAD

**Issue by jaburcodes** [dexfs/entria-challenge-fullstack#17]

**Comment by dexfs** [comment]
@jaburcodes do you have an example?  Or give me some tips how I can do it ?

**Comment by jaburcodes** [comment]
smthing like this: https://github.com/react-brasil/reactconfbr-app/blob/master/src/relay/RelayUtils.js

**Comment by dexfs** [comment]
@jaburcodes  
https://gist.github.com/dexfs/c6c0f0c44636090bb95a3dd0fce25556
http://recordit.co/BTx84O20QO

For some reason I don't know, it didn't render correctly. 
I modified a little bit, maybe there are something I can't see. 
When you need some time take a look please :D

**Comment by jaburcodes** [comment]
np, u're doing great!!
