### ISSUE TITLE
Cannot resolve module react-relay. 

### ISSUE THREAD

**Issue by dexfs** [dexfs/entria-challenge-fullstack#20]
Cannot resolve module styled-components/native.
```
     1│ // @flow
     2│ import React from 'react';
     3│ import styled from 'styled-components/native';
     4│
     5│ const StyledView = styled.View`
     6│     align-items: center;
```

RN Version - 0.54.0
flow-bin version 0.72.0

Isso ocorreu com mais de um modulo, eu não fiz nenhum tipo de alteração nas configs do flow,  se tiverem uma luz de como posso resolver isso eu agradeço 

@jaburcodes
@jgcmarins
@gsasouza

**Comment by jgcmarins** [comment]
Update styled-components version. Last one works with different import. You do not need to import as `styled-components/native`.

**Comment by sibelius** [comment]
`flow-typed install styled-components`
