### ISSUE TITLE
Add flow for type checking

### ISSUE THREAD

**Issue by jgcmarins** [dexfs/entria-challenge-fullstack#5]
- https://flow.org/

**Comment by dexfs** [comment]
@jgcmarins eu adicionei e fiz a configuração, porém não entendi como aplicar aos componentes que possuo teria alguma exemplo disso?

**Comment by dexfs** [comment]
#e475042f6aff3348dbed5f8528c74a43a0bbe14c 
#2fcd666e12f0203fa0780fbe1184aba5063113de
#a8a9efed0961240d7e3efed9fe7e070f6ed86e80
#36085db6594a0548a91b58392f56461ea563c605
#86020be5c427e1228548492e29393cb00028da73

**Comment by dexfs** [comment]
Adicionado flow, commits de hoje. 

Não consegui criar PR pois já existe uma aberta pra o branch atual.
